//
// Cforall Version 1.0.0 Copyright (C) 2015 University of Waterloo
//
// The contents of this file are covered under the licence agreement in the
// file "LICENCE" distributed with Cforall.
//
// BasicKind.hpp -- Declares all kinds of basic types.
//
// Author           : Andrew Beach
// Created On       : Thu Apr 18 14:00:00 2024
// Last Modified By : Andrew Beach
// Last Modified On : Thu Apr 18 14:00:00 2024
// Update Count     : 0
//

#pragma once

namespace ast {

// GENERATED START, DO NOT EDIT
// GENERATED BY BasicTypes-gen.cpp
enum BasicKind {
	Bool,
	Char,
	SignedChar,
	UnsignedChar,
	ShortSignedInt,
	ShortUnsignedInt,
	SignedInt,
	UnsignedInt,
	LongSignedInt,
	LongUnsignedInt,
	LongLongSignedInt,
	LongLongUnsignedInt,
	SignedInt128,
	UnsignedInt128,
	uFloat16,
	uFloat16Complex,
	uFloat32,
	uFloat32Complex,
	Float,
	FloatComplex,
	uFloat32x,
	uFloat32xComplex,
	uFloat64,
	uFloat64Complex,
	Double,
	DoubleComplex,
	uFloat64x,
	uFloat64xComplex,
	uuFloat80,
	uFloat128,
	uFloat128Complex,
	uuFloat128,
	LongDouble,
	LongDoubleComplex,
	uFloat128x,
	uFloat128xComplex,
	NUMBER_OF_BASIC_TYPES,
	MAX_INTEGER_TYPE = UnsignedInt128,
};
// GENERATED END

}
